package mockdata

import "recipes-api/models"

var MockRecipe = models.Recipe{
	Name:               "Test Pizza",
	Ingredients:        []string{"Flour", "Tomato"},
	Instructions:       []string{"Mix", "Bake"},
	PrepTimeMinutes:    15,
	CookTimeMinutes:    20,
	Servings:           2,
	Difficulty:         "Easy",
	Cuisine:            "Italian",
	CaloriesPerServing: 300,
	Tags:               []string{"dinner"},
	UserID:             1,
	Image:              "pizza.jpg",
	Rating:             4.5,
	ReviewCount:        12,
	MealType:           []string{"dinner"},
}

var MockRecipes = []interface{}{
	models.Recipe{
		Name:               "Seed Pizza",
		Ingredients:        []string{"Flour", "Cheese"},
		Instructions:       []string{"Knead", "Bake"},
		PrepTimeMinutes:    10,
		CookTimeMinutes:    15,
		Servings:           1,
		Difficulty:         "Easy",
		Cuisine:            "Italian",
		CaloriesPerServing: 250,
		Tags:               []string{"quick"},
		UserID:             42,
		Image:              "pizza.png",
		Rating:             4.0,
		ReviewCount:        7,
		MealType:           []string{"lunch"},
	},
	models.Recipe{
		Name:               "Seed Salad",
		Ingredients:        []string{"Lettuce", "Tomato"},
		Instructions:       []string{"Chop", "Mix"},
		PrepTimeMinutes:    5,
		CookTimeMinutes:    0,
		Servings:           2,
		Difficulty:         "Easy",
		Cuisine:            "Mediterranean",
		CaloriesPerServing: 150,
		Tags:               []string{"vegan"},
		UserID:             99,
		Image:              "salad.png",
		Rating:             4.8,
		ReviewCount:        22,
		MealType:           []string{"dinner"},
	},
	models.Recipe{
		Name:               "Seed Pasta",
		Ingredients:        []string{"Flour", "Tomato"},
		Instructions:       []string{"Mix", "Bake"},
		PrepTimeMinutes:    15,
		CookTimeMinutes:    20,
		Servings:           2,
		Difficulty:         "Easy",
		Cuisine:            "Italian",
		CaloriesPerServing: 300,
		Tags:               []string{"dinner"},
		UserID:             1,
		Image:              "pasta.jpg",
		Rating:             4.5,
		ReviewCount:        12,
		MealType:           []string{"dinner"},
	},
}
